apiVersion: v1
kind: Pod
metadata:
  name: hashi-vault
  labels:
    name: hashi-vault
spec:
  containers:
  - name: vault
    image: vault:1.13.3
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"
    ports:
      - containerPort: 8200
